"""
Cross-Repository UIContext Encoding Contract Tests (Task 10.2).

Asserts:
1. Exact equality (tolerance 1e-6) between Python R^6 encoder and TypeScript runtime encoder
   using fixtures generated by edge-aui-framework/scripts/regen-context-fixture.mjs.
2. Strict non-imputation: missing context raises ValueError or increments exclusion counters.
3. Component bounds [0, 1] and validation contracts.
"""

import os
import sys
import json
from pathlib import Path
import numpy as np
import pytest

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "src")))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from context_encoding import (
    CONTEXT_VECTOR_DIM,
    ROUTE_VOCABULARY,
    ACTION_VOCABULARY,
    TASK_STEP_COUNTS,
    encode_ui_context,
    validate_context_vector,
    encode_context_batch,
    ContextValidationResult,
)

FIXTURE_PATH = (
    Path(__file__).resolve().parent / "fixtures" / "context_encoding_fixtures.json"
)


class TestContextEncodingContract:
    def test_fixture_file_exists(self):
        assert (
            FIXTURE_PATH.exists()
        ), f"Cross-repo fixture not found at {FIXTURE_PATH}. Run regen-context-fixture.mjs first."

    def test_cross_repo_parity_matches_typescript_within_1e6(self):
        """High-risk contract test: Python encoding matches runtime TypeScript encoding within 1e-6."""
        with open(FIXTURE_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)

        assert data["dimension"] == CONTEXT_VECTOR_DIM == 6
        assert list(data["routeVocabulary"]) == list(ROUTE_VOCABULARY)
        assert list(data["actionVocabulary"]) == list(ACTION_VOCABULARY)

        cases = data["cases"]
        assert len(cases) >= 5, "Fixture must contain comprehensive test cases"

        for case in cases:
            name = case["name"]
            ctx = case["context"]
            expected = np.array(case["expectedVector"], dtype=np.float32)

            actual = encode_ui_context(ctx)

            assert actual.shape == (6,), f"Failed shape for case '{name}'"
            np.testing.assert_allclose(
                actual,
                expected,
                rtol=1e-6,
                atol=1e-6,
                err_msg=f"Cross-repo parity failure for fixture case '{name}': actual={actual}, expected={expected}",
            )

    def test_missing_context_raises_without_zero_imputation(self):
        """Missing continuous context must never be silently imputed with zeros (ADR-001 / Task 10.2)."""
        with pytest.raises(ValueError, match="UIContext dictionary is required"):
            encode_ui_context(None)

        with pytest.raises(ValueError, match="UIContext dictionary is required"):
            encode_ui_context("invalid string type")

    def test_batch_encoding_counts_exclusions(self):
        valid_ctx = {
            "route": "Analytics",
            "primaryActionAvailable": True,
            "helpAvailable": True,
            "expandable": False,
            "taskId": "T1",
            "taskStepId": "T1-2",
            "availableActions": ["click", "change"],
        }
        batch = [valid_ctx, None, {"route": "Overview"}, None]

        matrix, retained, stats = encode_context_batch(batch)

        assert matrix.shape == (2, 6)
        assert retained == [0, 2]
        assert stats.total_examples == 4
        assert stats.encoded_examples == 2
        assert stats.excluded_missing_context == 2
        assert stats.excluded_invalid_vector == 0

    def test_vector_bounds_and_validation(self):
        vec = np.array([0.2, 1.0, 0.0, 1.0, 0.75, 0.5], dtype=np.float32)
        val = validate_context_vector(vec)
        assert val.valid is True
        assert len(val.errors) == 0

        # Out of bounds
        bad_vec = np.array([1.5, 0.0, 0.0, 0.0, 0.0, 0.0], dtype=np.float32)
        val_bad = validate_context_vector(bad_vec)
        assert val_bad.valid is False
        assert any("bounds" in err for err in val_bad.errors)

        # Non-finite
        nan_vec = np.array([0.0, np.nan, 0.0, 0.0, 0.0, 0.0], dtype=np.float32)
        val_nan = validate_context_vector(nan_vec)
        assert val_nan.valid is False
        assert any("finite" in err for err in val_nan.errors)

        # Wrong shape
        wrong_shape = np.zeros((7,), dtype=np.float32)
        val_shape = validate_context_vector(wrong_shape)
        assert val_shape.valid is False
        assert any("shape" in err for err in val_shape.errors)

    def test_task_progress_derivation(self):
        # T1 has 4 steps. Step 1 -> 0/4 = 0.0, Step 2 -> 1/4 = 0.25, Step 4 -> 3/4 = 0.75
        v1 = encode_ui_context({"route": "Overview", "taskId": "T1", "taskStepId": "T1-1"})
        assert v1[4] == 0.0

        v2 = encode_ui_context({"route": "Overview", "taskId": "T1", "taskStepId": "T1-2"})
        assert v2[4] == 0.25

        v4 = encode_ui_context({"route": "Overview", "taskId": "T1", "taskStepId": "T1-4"})
        assert v4[4] == 0.75

        # T2 has 2 steps. Step 1 -> 0/2 = 0.0, Step 2 -> 1/2 = 0.5
        v_t2 = encode_ui_context({"route": "Overview", "taskId": "T2", "taskStepId": "T2-2"})
        assert v_t2[4] == 0.5
